# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.9.1" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort

  #-   repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: 'v0.910'  # Use the sha / tag you want to point at
  #    hooks:
  #    -   id: mypy
  #        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.5.7" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
#- repo: https://github.com/PyCQA/pydocstyle
#  rev: '6.1.1'
#  hooks:
#    -   id: pydocstyle
#        language: python
#        types: [python]
#        args:
#         - --ignore=D102,D100,D101,D105,D212
