version: "3.9"
   
services:

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   env_file: pg_env.txt
  #   ports:
  #     - "5051:80"
  #   restart: always
  #   depends_on:
  #     - db
