version: "3"
   
services:

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: pg_env.txt
    ports:
      - "5051:80"
    restart: always
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/pgadmin4/data
      
  web:
    build: .
    container_name: django
    restart: always
    command: bash -c "
        python manage.py collectstatic --no-input
        && python manage.py migrate --no-input
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

