version: "3"
   
services:

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    env_file: pg_env.txt
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: pg_env.txt
    ports:
      - "5051:80"
    restart: always
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/pgadmin4/data
      
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: always
    command: bash -c "
        python manage.py collectstatic --no-input
        && python manage.py migrate --no-input
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

