# Generated by Django 4.0.1 on 2022-03-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buildings',
        ),
    ]
