# Generated by Django 4.0.1 on 2022-03-07 15:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_rename_name_building_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=4326),
        ),
    ]
