# Generated by Django 4.0.1 on 2022-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_complaint_problem_related_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainage',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
