# Generated by Django 4.0.1 on 2022-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_road_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewerline',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
