# Generated by Django 4.0.1 on 2022-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_sewerline_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissionline',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmissionline',
            name='transmission_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
