# Generated by Django 4.0.1 on 2022-03-08 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_sewerline_alter_drainage_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewerline',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                srid=4326),
        ),
    ]
