# Generated by Django 4.0.1 on 2022-03-17 05:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_electricpole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_required_type', models.CharField(choices=[
                 ('Normal', 'Normal'), ('Emergency', 'Emergency')], default='Normal', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
