# Generated by Django 4.0.1 on 2022-03-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0020_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='is_deleted',
            new_name='is_solved',
        ),
    ]
