# Generated by Django 4.0.1 on 2022-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0021_rename_is_deleted_complaint_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
