# Generated by Django 4.0.1 on 2022-03-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0022_alter_complaint_is_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='names',
            new_name='name',
        ),
    ]
