# Generated by Django 4.0.1 on 2022-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Geomatics Engineering', 'Geomatics Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering with Architecture Program', 'Civil Engineering with Architecture Program'), (
                'Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Other', 'Other')], default='Geomatics Engineering', max_length=50),
        ),
    ]
